# Generated by Django 3.1.5 on 2021-01-24 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('httpurl', models.URLField()),
                ('short_id', models.SlugField(primary_key=True, serialize=False)),
                ('count', models.IntegerField(default=-1)),
            ],
        ),
    ]
